import express from "express";
import path from "path";
import fs from "fs";
import { createServer as createViteServer } from "vite";
import jwt from "jsonwebtoken";
import jwksClient from "jwks-rsa";
import firebaseConfig from "./firebase-applet-config.json";

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "20mb" }));
app.use(express.urlencoded({ extended: true, limit: "20mb" }));

// -------------------------------------------------------------
// SECURE GOOGLE APPS SCRIPT BACKEND INTEGRATION
// -------------------------------------------------------------
const GOOGLE_APPS_SCRIPT_URL = process.env.GOOGLE_APPS_SCRIPT_URL;
const API_SECRET = process.env.API_SECRET;

const jwks = jwksClient({
  jwksUri: "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"
});

function getKey(header: jwt.JwtHeader, callback: jwt.SigningKeyCallback) {
  jwks.getSigningKey(header.kid, function(err, key) {
    if (err || !key) {
      return callback(err || new Error("Key not found"));
    }
    const signingKey = key.getPublicKey();
    callback(null, signingKey);
  });
}

// Middleware to verify Firebase ID Token
const requireAuth = (req: any, res: any, next: any) => {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return res.status(401).json({ error: "Missing or invalid Authorization header" });
  }
  const token = authHeader.split(" ")[1];
  
  jwt.verify(token, getKey, {
    audience: firebaseConfig.projectId,
    issuer: `https://securetoken.google.com/${firebaseConfig.projectId}`,
    algorithms: ["RS256"]
  }, (err, decoded) => {
    if (err) {
      return res.status(401).json({ error: "Unauthorized: Invalid token" });
    }
    req.user = decoded;
    next();
  });
};

// Helper to call Apps Script
async function callAppsScript(action: string, payload?: any, method: string = "POST") {
  if (!GOOGLE_APPS_SCRIPT_URL || !API_SECRET) {
    throw new Error("Server not configured for Apps Script backend. Missing GOOGLE_APPS_SCRIPT_URL or API_SECRET.");
  }
  
  const url = `${GOOGLE_APPS_SCRIPT_URL}?secret=${encodeURIComponent(API_SECRET)}${method === "GET" ? `&action=${encodeURIComponent(action)}` : ""}`;
  
  const options: RequestInit = {
    method,
    headers: { "Content-Type": "application/json" }
  };
  
  if (method === "POST") {
    options.body = JSON.stringify({ action, payload });
  }

  const response = await fetch(url, options);
  if (!response.ok) {
    throw new Error(`Apps Script Error: ${response.statusText}`);
  }
  return await response.json();
}

app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", time: new Date().toISOString() });
});

// 1. Central Document Registry via Apps Script
app.get("/api/documents", requireAuth, async (req, res) => {
  try {
    const data = await callAppsScript("getDocuments", null, "GET");
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.post("/api/documents", requireAuth, async (req, res) => {
  try {
    // Audit log should be generated by frontend or apps script
    const data = await callAppsScript(req.body.action, req.body.payload, "POST");
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// 2. Central Staff & Roles Directory
app.get("/api/staff", requireAuth, async (req, res) => {
  try {
    const data = await callAppsScript("getStaff", null, "GET");
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.post("/api/staff", requireAuth, async (req: any, res) => {
  try {
    const data = await callAppsScript(req.body.action, req.body.payload, "POST");
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// 3. Audit Log Writing
app.post("/api/audit", requireAuth, async (req: any, res) => {
  try {
    const data = await callAppsScript("logAudit", req.body, "POST");
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// 4. Dedicated Institutional Links (Using Apps Script for central links)
app.get("/api/links", requireAuth, async (req, res) => {
  try {
    const data = await callAppsScript("getLinks", null, "GET");
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

app.post("/api/links", requireAuth, async (req, res) => {
  try {
    const data = await callAppsScript("saveLinks", req.body, "POST");
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ success: false, error: err.message });
  }
});

// -------------------------------------------------------------
// VITE SPA / STATIC SERVING
// -------------------------------------------------------------
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`POSSD Tracker backend running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
